todolist/todoapp/urls.py
from django.urls import path, re_path
from todoapp.auth import *
from todoapp.classbasedviews import *
from todoapp.apiviews import *

app_name = "todoapp"

urlpatterns = [
    path("list/", Todolistview.as_view(), name="list"),
    path("list/add/", CreateList.as_view(), name="create_list"),
    path("list/<int:pk>/edit", Editlist.as_view(), name="edit_list"),
    path("list/<int:pk>/delete", DeleteList.as_view(), name="delete_list"),
    path("apilist/", dislay),
    path("apilistmodify/<int:pk>/", modification_detail),
    path("signup/", Signupclass.as_view(), name="signup"),
    path("login/", LoginClass.as_view(), name="login"),
    path("logout/", logout_user, name="logout"),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from todoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('todoapp.urls')),
]

todolist/todoapp/models.py
from django.db import models
import datetime


# Create your models here.
class Todo_info(models.Model):
    task_title = models.CharField(max_length=128)
    task_info = models.TextField()
    actual_date = models.DateTimeField()
    status = models.CharField(max_length=128)

    def __str__(self):
        return self.task_title

todolist/todoapp/forms.py
from django import forms
from todoapp.models import *


class Addlist(forms.ModelForm):
    class Meta:
        model = Todo_info
        exclude = ['id']
        widgets = {
            'task_title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter title'}),
            'task_info': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter taskinfo'}),
            'actual_date': forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S',
                                               attrs={'class': 'form-control', 'placeholder': 'Enter date and time'}),
            'status': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter status'}),
        }


class Signupform(forms.Form):
    first_name = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Firstname'})
    )
    last_name = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Lastname'})
    )
    username = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'})
    )
    password = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'})
    )


class Loginform(forms.Form):
    username = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'})
    )
    password = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'})
    )

todolist/todoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from todoapp.models import *

todolist/todoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/solar/bootstrap.min.css">
</head>
<body>
<nav style="background:blue" class="navbar navbar-inverse">
    <!--<marquee scrollamount="12" direction="right" style="font-size:20px;color:yellow">BY  AJAYKUMAR MOVVA(AjayKing)</marquee>-->
    {% if request.user.is_authenticated %}
    <button style="float:right;margin-right:80px;margin-top:20px"><a href="{% url 'todoapp:logout' %}"class="btn btn-default active;btn btn-primary btn-sm">Logout</a></button>
    {% endif %}
</nav>
<div class="container">
{% block content %}
{% endblock content %}
</div>
</body>
</html>

todolist/todoapp/templates/errorpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INVALID</title>
</head>
<body>
    <h1>NOT VALID</h1>
</body>
</html>

todolist/todoapp/templates/loginform.html
{% extends "base.html"%}

{% block content %}
<div class="container">
    <h2>User Login:</h2>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <input style="margin-top:20px;height:35px;width:70px;margin-right:20px;color:white;background:black" type="submit" value="Login"/>
         <button style="background-color:black"><a href="{% url 'todoapp:signup' %}" class="btn btn-default active;btn btn-info btn-sm">Signup</a></button>
    </form>
</div>
{% endblock %}

todolist/todoapp/templates/signupform.html
{% extends "base.html"%}

{% block content %}
<div class="container">
    <h2>Create Newuser:</h2>
<form method="post">
    {% csrf_token %}
    {{form}}
    <input style="margin-top:20px;height:35px;width:70px;margin-right:20px;color:white;background:black" type="submit" value="Signup"/>
    <button style="background-color:black" ><a href="{% url 'todoapp:login' %}" class="btn btn-default active;btn btn-info btn-sm">Login</a></button>
</form>

</div>
{% endblock %}

todolist/todoapp/templates/tododetails.html
{% extends "base.html"%}

{% block content %}

<div class="container">
        <h2 align="center">List-INFORMATION</h2>
    {% if 'todoapp.add_todoinfo' in user_permissions %}
    <button  ><a style=" background-color:black,color:white" href="{% url 'todoapp:create_list' %}" class="btn btn-default active;btn btn-info btn-sm">+ AddCard</a></button>
    {% endif %}
        <center>
    <table class="table table-hover">
        <tr>
            <th>Title</th>
            <th>Info</th>
            <th>Date</th>
            <th>Status</th>
            {% if 'todoapp.change_todo_info' in user_permissions and 'todoapp.delete_todo_info' in user_permissions %}
            <th>operations</th>
            {% endif %}
        </tr>
        {% for obj in object %}
        <tr>
            <td>{{obj.task_title}}</td>
            <td>{{obj.task_info}}</td>
            <td>{{obj.actual_date}}</td>
            <td>{{obj.status}}</td>
             {% if 'todoapp.change_todo_info' in user_permissions and 'todoapp.delete_todo_info' in user_permissions %}
            <td ><a href="{% url 'todoapp:edit_list' obj.id %}" class="btn btn-default active;btn btn-info btn-sm">edit</a>    <a
                    href="{% url 'todoapp:delete_list' obj.id %}" class="btn btn-default active;btn btn-info btn-sm">delete</a>
                </td>
            {% endif %}
        </tr>
        {% endfor %}
        </table>
</center>
</div>
{% endblock %}

todolist/todoapp/templates/todoform.html
{% extends "base.html"%}

{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Add"/>
</form>
</div>
{% endblock %}